"""Added StringInt Table

Peek Plugin Database Migration Script

Revision ID: 02fbbd9bcb49
Revises: 
Create Date: 2020-05-01 23:15:20.571386

"""

# revision identifiers, used by Alembic.
revision = '02fbbd9bcb49'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StringIntTuple',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('string1', sa.String(), nullable=True),
    sa.Column('int1', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_tutorial'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StringIntTuple', schema='pl_tutorial')
    # ### end Alembic commands ###
