"""Added Setting Table

Peek Plugin Database Migration Script

Revision ID: 6b78eac0c2c0
Revises: d993c7cacf35
Create Date: 2020-05-01 19:28:48.389819

"""

# revision identifiers, used by Alembic.
revision = '6b78eac0c2c0'
down_revision = 'd993c7cacf35'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
