"""Added StringInt Table

Peek Plugin Database Migration Script

Revision ID: 913e5576323d
Revises: 450e040742f8
Create Date: 2020-08-06 10:16:53.896198

"""

# revision identifiers, used by Alembic.
revision = '913e5576323d'
down_revision = '450e040742f8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

