"""Added Setting Table

Peek Plugin Database Migration Script

Revision ID: 9b3b9fd6ffde
Revises: 913e5576323d
Create Date: 2020-08-06 10:21:46.774517

"""

# revision identifiers, used by Alembic.
revision = '9b3b9fd6ffde'
down_revision = '913e5576323d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

