"""Added StringInt Table

Peek Plugin Database Migration Script

Revision ID: d993c7cacf35
Revises: 
Create Date: 2020-05-01 19:27:18.887196

"""

# revision identifiers, used by Alembic.
revision = 'd993c7cacf35'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_tutorial'
    )
    op.create_table('StringIntTuple',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('string1', sa.String(length=50), nullable=True),
    sa.Column('int1', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_tutorial'
    )
    op.create_table('SettingProperty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('settingId', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('int_value', sa.Integer(), nullable=True),
    sa.Column('char_value', sa.String(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['settingId'], ['pl_tutorial.Setting.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_tutorial'
    )
    op.create_index('idx_SettingProperty_settingId', 'SettingProperty', ['settingId'], unique=False, schema='pl_tutorial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_SettingProperty_settingId', table_name='SettingProperty', schema='pl_tutorial')
    op.drop_table('SettingProperty', schema='pl_tutorial')
    op.drop_table('StringIntTuple', schema='pl_tutorial')
    op.drop_table('Setting', schema='pl_tutorial')
    # ### end Alembic commands ###
